#!/usr/bin/env bash
if [ -f "var/2015-11-21-raspbian-jessie-lite.img" ];
then
    echo "2015-11-21-raspbian-jessie-lite.img exists in cache"
else
    wget "https://kragniz.eu/pub/2015-11-21-raspbian-jessie-lite.img.xz"
    unxz "2015-11-21-raspbian-jessie-lite.img.xz"
    mv *.img var
fi
