#!/usr/bin/env bash
if [ ! -f "2015-11-21-raspbian-jessie-lite.img" ]; then
    wget "https://kragniz.eu/pub/2015-11-21-raspbian-jessie-lite.img.xz"
    unxz "2015-11-21-raspbian-jessie-lite.img.xz"
fi
