#!/usr/bin/env bash

set -xe

if [ "$#" -ne 1 ]; then
    echo "Not enough arguments. Usage: $0 <hostname>"
    exit 1
fi

host=$1

function check_ssh () {
    status=$(ssh -q $host echo ok 2>&1)
    if [[ $status == ok ]] ; then
        echo "Can connect using ssh"
    else
        echo "Can't connect with ssh to host $host"
        exit 1
    fi
}

function run () {
    command=$1
    ssh $host $command
}

check_ssh

run "mkdir -vp ~/dewi"

# copy local files - only copy files tracked by git
rsync -vaz --delete --max-size=10M ./ $host:~/dewi

