#!/usr/bin/env bash

set -xe

if [ "$#" -ne 1 ]; then
    command="redeploy"
    if [ "$#" -ne 2 ]; then
        echo "Not enough arguments. Usage: $0 <hostname> or $0 <hostname> provision"
        exit 1
    else
        command=$2
    fi
fi

host=$1

function check_ssh () {
    status=$(ssh -q $host echo ok 2>&1)
    if [[ $status == ok ]] ; then
        echo "Can connect using ssh"
    else
        echo "Can't connect with ssh to host $host"
        exit 1
    fi
}

function run () {
    cmd=$1
    ssh $host $cmd
}

check_ssh

run "mkdir -vp ~/dewi"

# install rsync
run "sudo apt-get install rsync"
# copy local files
rsync -va --no-inc-recursive --delete --max-size=10M --exclude 'dewi-hardware' ./ $host:~/dewi

if [ "$command" = "provision" ]; then
    run "cd ~/dewi; sudo ./host-provision"
fi

run "cd ~/dewi; sudo ./host-deploy"
