#!/usr/bin/env bash

set -xe

apt-get -y update
apt-get -y install \
    git \
    hostapd \
    isc-dhcp-server \
    picocom \
    python-dev \
    python-setuptools \
    screen \
    tmux \
    unzip \
    vim-nox \
    wget \
    python-pip \
    gpsd \
    python-gps

cp ./etc/boatd-config.yaml /etc

cp ./etc/boatd.service /etc/systemd/system/boatd.service
systemctl daemon-reload

cp ./etc/51-gps.rules /etc/udev/rules.d/
cp ./etc/52-arduino.rules /etc/udev/rules.d/
udevadm control --reload-rules

cp ./etc/hostname /etc/hostname
cp ./etc/motd /etc/motd

cp ./etc/dhcpd.conf /etc/dhcp/dhcpd.conf
cp ./etc/isc-dhcp-server /etc/default/isc-dhcp-server
cp ./etc/interfaces /etc/network/interfaces
cp ./etc/hostapd /etc/default/hostapd
cp ./etc/sysctl.conf /etc/sysctl.conf
mkdir -p /etc/hostapd
cp ./etc/hostapd.conf  /etc/hostapd/hostapd.conf
sed -i "s/PASSWORD/$(cat ./etc/password)/g" /etc/hostapd/hostapd.conf
