#!/usr/bin/env bash

apt-get -y update
apt-get -y install \
    hostapd \
    isc-dhcp-server \
    git \
    vim-nox \
    tmux \
    wget \
    unzip \

git clone https://github.com/kragniz/dot-files.git
make -C dot-files

cp -v ./etc/dhcpd.conf /etc/dhcp/dhcpd.conf
cp -v ./etc/isc-dhcp-server /etc/default/isc-dhcp-server
cp -v ./etc/interfaces /etc/network/interfaces
cp -v ./etc/hostapd /etc/default/hostapd
cp -v ./etc/sysctl.conf /etc/sysctl.conf
cp -v ./etc/hostapd.conf  /etc/hostapd/hostapd.conf
sed -i '/PASSWORD/$(cat password)/g' /etc/dhcp/dhcpd.conf

ifconfig wlan0 192.168.11.1

sh -c "echo 1 > /proc/sys/net/ipv4/ip_forward"

iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
iptables -A FORWARD -i eth0 -o wlan0 -m state --state RELATED,ESTABLISHED -j ACCEPT
iptables -A FORWARD -i wlan0 -o eth0 -j ACCEPT

iptables-save > /etc/iptables.ipv4.nat

wget http://www.adafruit.com/downloads/adafruit_hostapd.zip 
unzip adafruit_hostapd.zip

if [[ ! -f /usr/sbin/hostapd.ORIG ]]; then
    mv -v /usr/sbin/hostapd /usr/sbin/hostapd.ORIG
fi

mv -v hostapd /usr/sbin
chmod 755 /usr/sbin/hostapd

service hostapd start
service isc-dhcp-server start
update-rc.d hostapd enable
update-rc.d isc-dhcp-server enable 
