#!/usr/bin/env bash

set -xe

apt-get -y update
apt-get -y install \
    arduino \
    git \
    hostapd \
    isc-dhcp-server \
    picocom \
    python-dev \
    python-setuptools \
    screen \
    tmux \
    unzip \
    vim-nox \
    wget

cp ./etc/51-gps.rules /etc/udev/rules.d/
cp ./etc/52-arduino.rules /etc/udev/rules.d/
udevadm control --reload-rules

cp ./etc/hostname /etc/hostname
cp ./etc/motd /etc/motd

cp ./etc/dhcpd.conf /etc/dhcp/dhcpd.conf
cp ./etc/isc-dhcp-server /etc/default/isc-dhcp-server
cp ./etc/interfaces /etc/network/interfaces
cp ./etc/hostapd /etc/default/hostapd
cp ./etc/sysctl.conf /etc/sysctl.conf
mkdir -p /etc/hostapd
cp ./etc/hostapd.conf  /etc/hostapd/hostapd.conf
sed -i "s/PASSWORD/$(cat ./etc/password)/g" /etc/hostapd/hostapd.conf

ifconfig wlan0 192.168.11.1

sh -c "echo 1 > /proc/sys/net/ipv4/ip_forward"

iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
iptables -A FORWARD -i eth0 -o wlan0 -m state --state RELATED,ESTABLISHED -j ACCEPT
iptables -A FORWARD -i wlan0 -o eth0 -j ACCEPT

iptables-save > /etc/iptables.ipv4.nat

wget http://www.adafruit.com/downloads/adafruit_hostapd.zip 
unzip -fo adafruit_hostapd.zip
rm adafruit_hostapd.zip

if [[ ! -f /usr/sbin/hostapd.ORIG ]]; then
    mv -v /usr/sbin/hostapd /usr/sbin/hostapd.ORIG
fi

mv -v hostapd /usr/sbin
chmod 755 /usr/sbin/hostapd

service hostapd start
service isc-dhcp-server start
update-rc.d hostapd enable
update-rc.d isc-dhcp-server enable

git clone git://github.com/amperka/ino.git
pushd ino
sudo python setup.py install
popd

sudo wget https://raw.github.com/lurch/rpi-serial-console/master/rpi-serial-console -O /usr/bin/rpi-serial-console
sudo chmod +x /usr/bin/rpi-serial-console
sudo rpi-serial-console disable
